### PR TITLE
LPS-77158-PR

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @NemethNorbert,

As I said in [this PR](https://github.com/antonio-ortega/liferay-portal/pull/46#issuecomment-370883807), could you review all the cases are covered by this changes, please?

Thank you.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega ,

Thank you for investigating, I`ll start reviewing it.

**Comment by antonio-ortega** [comment]
After talking to you and Chema, I've sent the (expected) final pull request in jbalsas#1068

**Comment by NemethNorbert** [comment]
Hey Antonio,

Thanks for the email.

*Norbert Németh*
Technical Support Engineer

Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary
<https://maps.google.com/?q=Hungary+%7C+Madar%C3%A1sz+Viktor+u.+47.,+1138,+Budapest,+Hungary&entry=gmail&source=g>

**Pull request closed without merging**
